// <auto-generated />
namespace Truck.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assignment_return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assignment_return));
        
        string IMigrationMetadata.Id
        {
            get { return "201702241856448_assignment_return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
