// <auto-generated />
namespace Truck.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adjustment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustment));
        
        string IMigrationMetadata.Id
        {
            get { return "201702211534101_adjustment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
